# version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  # db:
  #   image: postgres:latest
  #   container_name: postgres
  #   environment:
  #     POSTGRES_DB: app
  #     POSTGRES_USER: app
  #     POSTGRES_PASSWORD: changethis123
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   env_file:
  #     - ./backend/.env
  #   restart: always

  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   ports:
  #     - "8080:8080" # Adminer port
  #   restart: always

  proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy_manager
    ports:
      - "80:80"
      - "443:443"
      - "8090:81" # Proxy Manager UI port
    volumes:
      - proxy_manager_data:/data
      - proxy_manager_letsencrypt:/etc/letsencrypt
    restart: always

volumes:
  # postgres_data:
  proxy_manager_data:
  proxy_manager_letsencrypt: